/*
 * Builds synthetic Windows PE images for the tests.
 *
 * These are real images, not mocks: the analyzer under test parses them with the
 * same code path it uses on a retail executable. A stub that returned
 * pre-cooked facts would test the stub. The trade-off is that this file has to
 * emit a correct PE, which is why the layout is spelled out byte by byte below
 * rather than generated by a library -- a second PE writer would be one more
 * thing to be wrong about the format.
 *
 *   offset  contents
 *   0x000   DOS header, e_lfanew = 0x40
 *   0x040   "PE\0\0", COFF header, PE32+ optional header (240 bytes)
 *   0x134   section table, up to 4 sections of 40 bytes
 *   0x200   .rdata   RVA 0x1000: imports, strings, DXBC blobs, CLR header
 *   0x600   .text    RVA 0x2000
 *   0x800   .data    RVA 0x3000
 *
 * File alignment is 0x200 throughout, so an RVA inside .rdata at or above 0x1000
 * maps to 0x200 + (rva - 0x1000).
 */
#ifndef MR_FIXTURE_H
#define MR_FIXTURE_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#define MR_FIXTURE_CAPACITY (64u * 1024u)
#define MR_FIXTURE_RDATA_RVA 0x1000u
#define MR_FIXTURE_RDATA_OFF 0x200u
#define MR_FIXTURE_TEXT_RVA 0x2000u
#define MR_FIXTURE_TEXT_OFF 0x600u
#define MR_FIXTURE_DATA_RVA 0x3000u
#define MR_FIXTURE_DATA_OFF 0x800u

#define MR_FIXTURE_MAX_IMPORTS 16
#define MR_FIXTURE_MAX_SYMBOLS 8

typedef struct {
  const char *module;
  const char *symbols[MR_FIXTURE_MAX_SYMBOLS];
  size_t symbol_count;
} mr_fixture_import;

typedef struct {
  uint8_t bytes[MR_FIXTURE_CAPACITY];
  size_t len;

  uint16_t machine;      /* 0x8664 by default */
  uint16_t subsystem;    /* 2 = GUI, 3 = console */
  uint16_t characteristics; /* 0x0022 = executable, large address aware */

  mr_fixture_import imports[MR_FIXTURE_MAX_IMPORTS];
  size_t import_count;

  /* Section names, appended in order after the default three. */
  const char *extra_sections[4];
  size_t extra_section_count;

  /* Payload for .rdata, appended after the import table. */
  uint8_t rdata_tail[4096];
  size_t rdata_tail_len;

  bool with_clr_header;
  const char *clr_version; /* e.g. "v4.0.30319" */
} mr_fixture;

/* Resets `f` to a plain x86-64 GUI executable with the three standard sections
 * and no imports. */
void mr_fixture_init(mr_fixture *f);

/* Appends an import descriptor. `module` is stored as-is; the analyzer lowercases
 * it, and the fixture deliberately does not, so the test exercises that. */
bool mr_fixture_add_import(mr_fixture *f, const char *module,
                           const char *const *symbols, size_t symbol_count);

/* Appends a DXBC or DXIL container marker to the .rdata payload. Counting magic
 * words is what the analyzer does, so a marker alone is what it sees. */
void mr_fixture_add_blob(mr_fixture *f, const char *magic, size_t payload_len);

/* Adds a section header. The section body is zero-filled; only the name, RVA and
 * sizes matter to the checks under test. */
bool mr_fixture_add_section(mr_fixture *f, const char *name);

/* Enables a CLR header whose metadata root carries `version`. */
void mr_fixture_set_clr(mr_fixture *f, const char *version);

/* Renders the image into f->bytes and sets f->len. Returns false on overflow. */
bool mr_fixture_build(mr_fixture *f);

/* Writes the built image to `path`. */
bool mr_fixture_write(const mr_fixture *f, const char *path);

/* Convenience: a plain x86-64 Direct3D 11 executable that links d3d11.dll and
 * calls D3D11CreateDeviceAndSwapChain. */
void mr_fixture_d3d11(mr_fixture *f);

/* A 32-bit image. */
void mr_fixture_i386(mr_fixture *f);

/* An image with kernel-level anti-cheat linked. */
void mr_fixture_anticheat(mr_fixture *f);

#endif /* MR_FIXTURE_H */
