#!/bin/bash
# Stage Wine's codepage tables (c_*.nls) into the app bundle's nls folder.
#
# The complete set is CHECKED INTO THE WINE SOURCE TREE (`wine/nls/*.nls` --
# 76 files at the pinned revision: 68 codepages plus locale, l_intl, norm* and
# sortdefault). They are not generated by `make`; the build tree copies them.
# The submodule that ships the loader is therefore also the source of truth for
# the tables it reads, and app/Madeira/nls/ carries the same 76 as committed
# files. This script re-copies them from the pinned source so a Wine bump
# refreshes the tables instead of leaving a stale pair behind.
#
# ml809 -- WHY THIS SHIPPED FOUR CODEPAGES OUT OF SIXTY-EIGHT.
#
# It looked for the tables in the build tree and asked whether that directory
# existed before deciding to build them:
#
#     sources=("$WINE_BUILD/nls")
#     if [[ -d "$WINE_BUILD" && -f "$WINE_BUILD/config.status" && ! -d "${sources[0]}" ]]; then
#         make -C "$WINE_BUILD" nls
#     fi
#
# configure CREATES nls/ (it writes nls/Makefile), so `! -d` was false on every
# configured tree, `make nls` never ran, the copy loop found no *.nls, and the
# script fell back to the four hand-committed tables with a line in the build
# log that reads like a warning and was read like one. The device saw the
# truth: a title asking ntdll for its own codepage (CP949, CP932, CP1251) gets
# STATUS_OBJECT_NAME_NOT_FOUND out of NtGetNlsSectionPtr, stalls in locale
# setup, and dies at startup with nothing in the log to say why. The test
# belongs on the FILES, not the directory -- a directory Wine created empty is
# not evidence that anything is in it.
#
# Best-effort by design: the archive check can pass without a Wine tree (a
# cache restore, a machine with pre-built libs), and a missing source must not
# fail the package. What it must not do is report success over four tables when
# sixty-eight are sitting right there, so the counts are checked against the
# source when a source was available, and a shortfall is an error.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$ROOT/app/Madeira/nls"
WINE_SRC="${WINE_SRC:-$ROOT/wine}"
WINE_BUILD="${WINE_BUILD:-$WINE_SRC/build-macos}"

mkdir -p "$DEST"

# Where the tables come from, in the order we prefer them. The source tree
# first: its tables are committed, so they exist the moment the submodule is
# checked out and do not depend on how far a `make` got.
sources=("$WINE_SRC/nls" "$WINE_BUILD/nls")

have_tables() { [[ -n "$(compgen -G "$1/*.nls" 2>/dev/null || true)" ]]; }

# Only when neither tree has a single table is it worth asking make for them.
if ! have_tables "${sources[0]}" && ! have_tables "${sources[1]}" \
    && [[ -f "$WINE_BUILD/config.status" ]]; then
    echo "stage-nls: no .nls tables in either tree; asking the build tree for the nls target."
    JOBS="${JOBS:-${BUILD_JOBS:-4}}"
    if make -C "$WINE_BUILD" -j"$JOBS" nls 2>&1 | tail -n 20; then
        :
    else
        echo "stage-nls: WARNING -- 'make nls' failed; keeping the committed tables only." >&2
    fi
fi

copied=0
for src in "${sources[@]}"; do
    have_tables "$src" || continue
    for f in "$src"/*.nls; do
        name="$(basename "$f")"
        cp -f "$f" "$DEST/$name"
        copied=$((copied + 1))
    done
    echo "stage-nls: refreshed $copied table(s) from $src"
    break
done

if [[ "$copied" -eq 0 ]]; then
    echo "stage-nls: no source tables available; keeping the committed set." >&2
fi

# Report what will ship, and check it against what the source offered rather
# than a hard-coded number, so a Wine bump cannot quietly move the target: the
# count that matters is "everything the pinned tree has".
count=$(find "$DEST" -maxdepth 1 -name 'c_*.nls' | wc -l | tr -d ' ')
total=$(find "$DEST" -maxdepth 1 -name '*.nls' | wc -l | tr -d ' ')
echo "stage-nls: shipping $total NLS table(s), $count of them codepages"

src_count=0
for src in "${sources[@]}"; do
    have_tables "$src" || continue
    src_count=$(find "$src" -maxdepth 1 -name 'c_*.nls' | wc -l | tr -d ' ')
    break
done

if [[ "$src_count" -gt 0 && "$count" -lt "$src_count" ]]; then
    echo "stage-nls: ERROR -- the source tree has $src_count codepage tables but only" \
         "$count are staged. A title using a missing codepage fails in locale setup" \
         "with STATUS_OBJECT_NAME_NOT_FOUND and no other clue." >&2
    exit 1
fi
if [[ "$count" -lt 60 ]]; then
    echo "stage-nls: ERROR -- $count codepage tables is far below the 68 the pinned Wine" \
         "ships. Either stage from wine/nls (the submodule) or commit the full set." >&2
    exit 1
fi
