#!/usr/bin/env python3
"""Gate: the Metal 4 disposition map must cover the whole winemetal surface.

DXMT reaches Metal through exactly one seam, the winemetal unix-call table.
`research/dxmt/src/winemetal/wmt_api_names.h` is generated from that table and
is therefore the authoritative list of every Metal call the renderer can make.
`docs/metal4/winemetal-metal4-map.tsv` records, for each slot, what a Metal 4
port does with it.

Those two files are the plan. If a slot appears in the table that the map does
not classify, the plan is silently incomplete -- and the failure mode is worse
than a missing file, because a Metal 4 port driven by this map would port the
slots it knows about and leave the rest reaching for Metal 3 objects through the
Metal 4 path. A new slot is cheap to add and easy to miss: the table is
regenerated by a script, the map is hand-edited.

The check is a set comparison in both directions plus a vocabulary check, so an
extra, renamed or mistyped row fails as loudly as a missing one.

Skips (exit 0) when the DXMT submodule is not checked out, because a clean clone
has empty submodules and this gate must not be the reason such a clone cannot
run the rest of the suite.
"""

from __future__ import annotations

import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
NAMES_H = REPO_ROOT / "research/dxmt/src/winemetal/wmt_api_names.h"
MAP_TSV = REPO_ROOT / "docs/metal4/winemetal-metal4-map.tsv"
SUBMODULE = "research/dxmt"

# The map describes one revision of the DXMT submodule. Set equality on the slot
# names catches a rename, but a revision bump can add or remove behaviour while
# leaving the name list identical, so the recorded revision is checked too.
REVISION_LINE = re.compile(
    r"^#\s*Describes\s+" + re.escape(SUBMODULE)
    + r"\s+at the revision this tree records:\s*([0-9a-f]{7,40})\s*$",
    re.M,
)

DISPOSITIONS = {
    "mtl4-core",
    "mtl4-bind",
    "mtl4-compile",
    "shared",
    "dxmt-internal",
    "host-only",
}

# Slot names in the header are the quoted strings of the wmt_api_names[] array.
QUOTED = re.compile(r'^\s*"((?:[^"\\]|\\.)*)",\s*$', re.M)
COUNT_DEFINE = re.compile(r"^#define\s+WMT_API_COUNT\s+(\d+)\s*$", re.M)


def die(message: str) -> None:
    print(f"metal4-inventory: FAIL: {message}", file=sys.stderr)
    sys.exit(1)


def read_slots() -> list[str]:
    text = NAMES_H.read_text()
    declared = COUNT_DEFINE.search(text)
    if not declared:
        die(f"{NAMES_H} has no WMT_API_COUNT define; the header is not the expected shape")
    slots = [m.group(1) for m in QUOTED.finditer(text)]
    expected = int(declared.group(1))
    if len(slots) != expected:
        die(
            f"{NAMES_H} declares WMT_API_COUNT {expected} but lists {len(slots)} names; "
            "the generated header is internally inconsistent"
        )
    return slots


def read_map() -> tuple[str, list[tuple[str, str, str]]]:
    text = MAP_TSV.read_text()
    match = REVISION_LINE.search(text)
    if not match:
        die(
            f"{MAP_TSV} has no '# Describes {SUBMODULE} at the revision this tree records: <sha>' "
            "line, so the map is not tied to a revision"
        )
    revision = match.group(1)
    rows: list[tuple[str, str, str]] = []
    for lineno, raw in enumerate(text.splitlines(), 1):
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        fields = raw.split("\t")
        if len(fields) < 2:
            die(f"{MAP_TSV}:{lineno}: expected at least 'slot<TAB>disposition', got {raw!r}")
        rows.append((fields[0], fields[1], fields[2] if len(fields) > 2 else ""))
    if not rows:
        die(f"{MAP_TSV} has no rows")
    return revision, rows


def recorded_revision() -> str | None:
    """The DXMT gitlink in the index, or None if git cannot be consulted."""
    try:
        out = subprocess.run(
            ["git", "-C", str(REPO_ROOT), "ls-files", "-s", "--", SUBMODULE],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.split()
    except (OSError, subprocess.CalledProcessError):
        return None
    return out[1] if len(out) >= 2 else None



def main() -> int:
    if not NAMES_H.exists():
        print(
            "metal4-inventory: SKIP: "
            f"{NAMES_H.relative_to(REPO_ROOT)} is absent (DXMT submodule not checked out).",
            file=sys.stderr,
        )
        return 0
    if not MAP_TSV.exists():
        die(f"{MAP_TSV} is missing but the winemetal surface is present")

    slots = read_slots()
    map_revision, rows = read_map()

    recorded = recorded_revision()
    if recorded is None:
        print(
            "metal4-inventory: WARN: git could not report the "
            f"{SUBMODULE} gitlink; skipping the revision-pin check.",
            file=sys.stderr,
        )
    elif not recorded.startswith(map_revision):
        die(
            f"{MAP_TSV} describes {SUBMODULE} at {map_revision}, but this tree records "
            f"{recorded}. The map is stale: re-check the winemetal surface at the new "
            "revision and re-classify before trusting the Metal 4 plan."
        )

    slot_set = set(slots)
    row_names = [name for name, _, _ in rows]
    row_set = set(row_names)

    if len(row_names) != len(row_set):
        duplicates = sorted(n for n, c in Counter(row_names).items() if c > 1)
        die(f"{MAP_TSV} classifies the same slot twice: {duplicates}")

    unknown = sorted({d for _, d, _ in rows} - DISPOSITIONS)
    if unknown:
        die(
            "unknown disposition(s): "
            f"{unknown}; expected one of {sorted(DISPOSITIONS)}"
        )

    missing = sorted(slot_set - row_set)
    extra = sorted(row_set - slot_set)
    if missing:
        die(
            f"{len(missing)} winemetal slot(s) the map does not classify: {missing}. "
            f"Add a row to {MAP_TSV.relative_to(REPO_ROOT)}."
        )
    if extra:
        die(
            f"{len(extra)} map row(s) name a slot that is not in the winemetal table: {extra}. "
            "The table was regenerated and these slots were renamed or removed."
        )

    counts = Counter(d for _, d, _ in rows)
    changes = counts["mtl4-core"] + counts["mtl4-bind"] + counts["mtl4-compile"]
    print(f"metal4-inventory: {len(slots)} winemetal slots, all classified")
    print(
        f"metal4-inventory:   needs Metal 4 work ... {changes} "
        f"(core {counts['mtl4-core']}, bind {counts['mtl4-bind']}, compile {counts['mtl4-compile']})"
    )
    print(f"metal4-inventory:   unchanged by Metal 4 ... {counts['shared']}")
    print(
        f"metal4-inventory:   not Metal .......... "
        f"{counts['dxmt-internal'] + counts['host-only']} "
        f"(dxmt-internal {counts['dxmt-internal']}, host-only {counts['host-only']})"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
