#!/bin/sh
# Tests for the app side of the virtual XInput pad (app/Madeira/MadeiraXInput.c).
#
# Two things are checked, and neither is visible from a build that succeeds.
#
# 1. The ABI. `struct madeira_pad_state` is written twice: once in the app
#    (MadeiraXInput.h, arm64) and once in the guest's xinput1_4.dll
#    (patches/wine-xinput-virtual-pad.patch, arm64ec). Both comments say they
#    must stay byte-for-byte identical and nothing enforced it: a field added,
#    reordered or resized here would compile in both places and hand the guest
#    garbage -- sticks reading buttons. The patch's own definitions are
#    extracted here and compared by the compiler, through sizeof/offsetof,
#    rather than by eye.
#
# 2. The table. `madeira_xinput_unix_call_table()` is dispatched by index from
#    the guest (ntdll's __wine_unix_call), so the order is the ABI and an
#    appended entry would silently redirect XInputGetState. The test calls
#    through the table the way ntdll does and checks the frame, the packet
#    number, the disconnected case, and that rumble reaches the app without
#    ever failing the game.
#
# Needs a C compiler: cc by default, override with CC=.
set -eu
ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$ROOT"

CC=${CC:-}
if [ -z "$CC" ]; then
    for candidate in cc clang gcc; do
        if command -v "$candidate" >/dev/null 2>&1; then
            CC=$candidate
            break
        fi
    done
fi
if [ -z "$CC" ] || ! command -v "$CC" >/dev/null 2>&1; then
    echo "test-xinput-pad: SKIP -- no C compiler on PATH (override with CC=...)" >&2
    exit 0
fi

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

# The guest's half of the ABI, lifted out of the patch. Struct names are
# prefixed so both definitions can live in one translation unit; the field
# names are left alone, because those are what the offsets are compared by.
python3 - patches/wine-xinput-virtual-pad.patch "$TMP/wine-side-abi.h" <<'PY'
import re
import sys

patch = open(sys.argv[1]).read()
out = ['/* Generated by tools/test-xinput-pad.sh from patches/wine-xinput-virtual-pad.patch. */\n',
       '#ifndef WINE_SIDE_ABI_H\n#define WINE_SIDE_ABI_H\n\n']
for name in ('madeira_pad_state', 'madeira_pad_rumble'):
    match = re.search(r'^\+struct %s\n(.*?)^\+\};$' % name, patch, re.M | re.S)
    if not match:
        sys.exit(f'FAILED: the patch declares no struct {name}; the test cannot compare the ABI.')
    body = ''.join(line[1:] + '\n' for line in match.group(1).splitlines())
    out.append(f'struct wine_{name}\n{body}}};\n\n')
out.append('#endif /* WINE_SIDE_ABI_H */\n')
open(sys.argv[2], 'w').write(''.join(out))
print('extracted the guest-side ABI from patches/wine-xinput-virtual-pad.patch')
PY

cat > "$TMP/main.c" <<'C'
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "MadeiraXInput.h"
#include "wine-side-abi.h"

static int failures;
static int checks;

static void check_int(const char *label, long got, long want)
{
    checks++;
    if (got != want) failures++;
    printf("  %s %s: got %ld, want %ld\n", got == want ? "ok  " : "FAIL", label, got, want);
}

/* Every field, by name, in both definitions. An offset that moves without the
 * other side moving is the failure this whole file exists for. */
#define SAME_OFFSET(field) \
    check_int("offset of " #field, \
              (long)offsetof(struct madeira_pad_state, field), \
              (long)offsetof(struct wine_madeira_pad_state, field))

/* ntdll's __wine_unix_call: index into the table, hand it the argument. */
typedef int32_t (*unix_func)(void *);

static int32_t dispatch(const void *const *table, unsigned int code, void *arg)
{
    return ((unix_func)table[code])(arg);
}

#define STATUS_SUCCESS 0x00000000
#define STATUS_INVALID_PARAMETER ((int32_t)0xC000000D)
#define STATUS_DEVICE_NOT_CONNECTED ((int32_t)0xC000009C)

static uint16_t rumble_left, rumble_right;
static int rumble_calls;

static void on_rumble(uint16_t left, uint16_t right)
{
    rumble_left = left;
    rumble_right = right;
    rumble_calls++;
}

int main(void)
{
    const void *const *table = madeira_xinput_unix_call_table();
    struct madeira_pad_state state;
    struct madeira_pad_rumble rumble;

    printf("ABI:\n");
    check_int("state is 16 bytes in both definitions",
              (long)sizeof(struct madeira_pad_state),
              (long)sizeof(struct wine_madeira_pad_state));
    check_int("state is 16 bytes, spelled out", (long)sizeof(struct madeira_pad_state), 16);
    SAME_OFFSET(packet);
    SAME_OFFSET(buttons);
    SAME_OFFSET(left_trigger);
    SAME_OFFSET(right_trigger);
    SAME_OFFSET(thumb_lx);
    SAME_OFFSET(thumb_ly);
    SAME_OFFSET(thumb_rx);
    SAME_OFFSET(thumb_ry);
    check_int("rumble is 4 bytes in both definitions",
              (long)sizeof(struct madeira_pad_rumble),
              (long)sizeof(struct wine_madeira_pad_rumble));
    check_int("rumble has the same offset of left",
              (long)offsetof(struct madeira_pad_rumble, left),
              (long)offsetof(struct wine_madeira_pad_rumble, left));
    check_int("rumble has the same offset of right",
              (long)offsetof(struct madeira_pad_rumble, right),
              (long)offsetof(struct wine_madeira_pad_rumble, right));
    check_int("the function count is the ABI", MADEIRA_PAD_FUNC_COUNT, 2);
    check_int("get_state is index 0", MADEIRA_PAD_GET_STATE, 0);
    check_int("set_rumble is index 1", MADEIRA_PAD_SET_RUMBLE, 1);
    check_int("the table has an entry for every code",
              table[MADEIRA_PAD_GET_STATE] != NULL && table[MADEIRA_PAD_SET_RUMBLE] != NULL, 1);

    printf("no controller:\n");
    memset(&state, 0xAA, sizeof(state));
    check_int("an unpublished pad is disconnected",
              dispatch(table, MADEIRA_PAD_GET_STATE, &state), STATUS_DEVICE_NOT_CONNECTED);
    check_int("and reports no slot 0", madeira_xinput_unix_call_table() != NULL, 1);

    printf("one frame:\n");
    /* A and B, half a left trigger, right stick pushed right and up. */
    madeira_xinput_publish(0x3000, 128, 0, 0, 0, 32767, 16384);
    memset(&state, 0, sizeof(state));
    check_int("the frame is served",
              dispatch(table, MADEIRA_PAD_GET_STATE, &state), STATUS_SUCCESS);
    check_int("buttons survive", state.buttons, 0x3000);
    check_int("left trigger survives", state.left_trigger, 128);
    check_int("right trigger survives", state.right_trigger, 0);
    check_int("left stick survives", state.thumb_lx, 0);
    check_int("right stick x survives", state.thumb_rx, 32767);
    check_int("right stick y survives", state.thumb_ry, 16384);

    /* dwPacketNumber promises "changed only when the state did". A game that
     * compares packets to skip work reads a republished identical frame as
     * stillness, and an on-screen pad at rest republishes every tick. */
    {
        uint32_t first = state.packet;
        madeira_xinput_publish(0x3000, 128, 0, 0, 0, 32767, 16384);
        dispatch(table, MADEIRA_PAD_GET_STATE, &state);
        check_int("an unchanged frame keeps the packet number", state.packet == first, 1);
        madeira_xinput_publish(0x3001, 128, 0, 0, 0, 32767, 16384);
        dispatch(table, MADEIRA_PAD_GET_STATE, &state);
        check_int("a changed frame bumps it", state.packet != first, 1);
        check_int("and the change is visible", state.buttons, 0x3001);
    }

    printf("released:\n");
    madeira_xinput_clear();
    check_int("a cleared pad is disconnected",
              dispatch(table, MADEIRA_PAD_GET_STATE, &state), STATUS_DEVICE_NOT_CONNECTED);
    madeira_xinput_publish(0, 0, 0, 0, 0, 0, 0);
    check_int("publishing again reconnects it",
              dispatch(table, MADEIRA_PAD_GET_STATE, &state), STATUS_SUCCESS);

    printf("bad arguments:\n");
    check_int("a null state is rejected, not written",
              dispatch(table, MADEIRA_PAD_GET_STATE, NULL), STATUS_INVALID_PARAMETER);
    check_int("a null rumble is rejected",
              dispatch(table, MADEIRA_PAD_SET_RUMBLE, NULL), STATUS_INVALID_PARAMETER);

    printf("rumble:\n");
    rumble.left = 20000;
    rumble.right = 40000;
    madeira_xinput_set_rumble_handler(NULL);
    check_int("rumble with nobody listening still succeeds",
              dispatch(table, MADEIRA_PAD_SET_RUMBLE, &rumble), STATUS_SUCCESS);
    check_int("and calls nothing", rumble_calls, 0);
    madeira_xinput_set_rumble_handler(on_rumble);
    check_int("rumble reaches the app",
              dispatch(table, MADEIRA_PAD_SET_RUMBLE, &rumble), STATUS_SUCCESS);
    check_int("with both motors", rumble_left == 20000 && rumble_right == 40000, 1);
    check_int("once", rumble_calls, 1);
    madeira_xinput_set_rumble_handler(NULL);

    printf(failures == 0 ? "test-xinput-pad: OK (%d checks)\n"
                         : "test-xinput-pad: %d FAILURES (%d checks)\n",
           failures == 0 ? checks : failures, checks);
    return failures == 0 ? 0 : 1;
}
C

# -Wall -Wextra -Werror: the app file is compiled as the app compiles it, so a
# warning introduced here is a warning there.
"$CC" -std=c11 -Wall -Wextra -Werror -I"$ROOT/app/Madeira" -I"$TMP" \
    -o "$TMP/test-xinput-pad" "$TMP/main.c" "$ROOT/app/Madeira/MadeiraXInput.c"
"$TMP/test-xinput-pad"
